import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "@/app/providers";
import { cookies } from 'next/headers'
import {getDictionary} from "@/lib/lang/dictionary";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies()
  const lang = cookieStore.get('lang');
  const dictionary = await getDictionary(lang?.value || 'en')

  return (
    <html lang="en">
      <body className={inter.className + ' flex flex-col h-screen'}>
        <Providers options={{lang: lang?.value || 'en', dictionary}}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
